import Head from "next/head"
import Image from "next/image"

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main style={{ position: "relative" }}>
        {[...Array(50)].map((_, i) => (
          <p key={i}>{i}</p>
        ))}

        <Image src="/cat.jpg" alt="image" width={400} height={600} />
      </main>
    </>
  )
}
